version: "3.8"

services:
  python:
    image: esgimicroci/al1-docker-runner:latest
    volumes:
      - runner-data:/var/lib/project/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

volumes:
  runner-data: