version: "3.8"

services:
  python:
    image: esgimicroci/al1-docker-runner:latest
    volumes:
      - /micro-ci-docker-runner/projects-repository:/projects
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: always
    ports:
      - 8156:8156

volumes:
  runner-data: